import logging
from flask import Flask, jsonify, request
from google.cloud import storage
import random
import os
from flask_cors import CORS

logging.basicConfig(level=logging.INFO)

app = Flask(__name__)
CORS(app)

storage_client = storage.Client()
bucket_name = os.environ.get('CLOUD_STORAGE_BUCKET', 'random-numbers1')
bucket = storage_client.bucket(bucket_name)

GAE_INSTANCE = os.environ.get('GAE_INSTANCE', 'Unknown')
logging.info(f"GAE_INSTANCE: {GAE_INSTANCE}")

def fetch_random_numbers_from_bucket():
    numbers = []
    blobs = bucket.list_blobs(prefix='random_numbers/')
    for blob in blobs:
        try:
            data = blob.download_as_string().decode('utf-8')
            numbers.append(int(data))
        except Exception as e:
            logging.error(f"Error decoding random number from blob {blob.name}: {e}")
    return numbers

def store_random_number(random_number, instance_id):
    blob = bucket.blob(f'random_numbers/{instance_id}_{random_number}.txt')
    try:
        blob.upload_from_string(str(random_number))
        logging.info(f"Instance {instance_id} stored random number {random_number}")
    except Exception as e:
        logging.error(f"Instance {instance_id} error storing random number {random_number}: {e}")

@app.route('/')
def home():
    logging.info(f"Instance {GAE_INSTANCE} handling the request")
    return jsonify({'message': 'Backend is running'}), 200

@app.route('/delete_bucket_contents', methods=['POST'])
def delete_bucket_contents():
    try:
        blobs = bucket.list_blobs(prefix='random_numbers/')
        for blob in blobs:
            blob.delete()
        logging.info(f"Instance {GAE_INSTANCE} deleted bucket contents")
        return jsonify({'message': 'Bucket contents deleted successfully'}), 200
    except Exception as e:
        logging.error(f"Instance {GAE_INSTANCE} error deleting bucket contents: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/generate', methods=['GET'])
def generate_random_number():
    random_number = random.randint(0, 100000)
    store_random_number(random_number, GAE_INSTANCE)
    return jsonify({'randomNumber': random_number})

@app.route('/results', methods=['GET'])
def get_results():
    logging.info(f"Request received for results in instance {GAE_INSTANCE}")
    
    random_numbers = fetch_random_numbers_from_bucket()
    if not random_numbers:
        return jsonify({'message': 'No numbers generated yet'}), 200

    min_number = min(random_numbers)
    max_number = max(random_numbers)
    
    instances_count = {}
    blobs = bucket.list_blobs(prefix='random_numbers/')
    for blob in blobs:
        instance_id = blob.name.split('/')[1].split('_')[0]
        instances_count[instance_id] = instances_count.get(instance_id, 0) + 1
    
    output = f"Maximum: {max_number}\n"
    output += f"Minimum: {min_number}\n"
    output += "Total Numbers Generated By Each Instance\n"
    for instance_id, count in instances_count.items():
        output += f"Instance {instance_id} generated {count} numbers\n"
    
    logging.info(f"Calculated results: \n{output}")
    
    return jsonify({
        'output': output,
        'min': min_number,
        'max': max_number,
    })

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=8080)
